In [13]:

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

model = LinearRegression()
X = [[1], [2], [3], [4]] # Features
y = [2, 4, 5, 4]       # Target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_test)
print(X_train)
print(y_train)
print(y_test)
model.fit(X, y)
new_data = [[5]]
prediction = model.predict(new_data)
y_pred = model.predict(X_test)




[[2]]
[[4], [1], [3]]
[4, 2, 5]
[4]


In [ ]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Sample training data
X_train = np.array([[1], [2], [3], [4]])
y_train = np.array([2, 4, 5, 4])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train a linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# New data for prediction
X_new = np.array([[5]])

# Make predictions
predictions = model.predict(X_new)
print(predictions)

[[4], [1], [3]]
[5.5]


In [17]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 1. Loading the Dataset
iris = load_iris()
X = iris.data
y = iris.target

# 2. Splitting the Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

# 3. Training the Model
log_reg = LogisticRegression(max_iter=200) # Creating a logistic regression classifier object
log_reg.fit(X_train, y_train) # Training the model with the training data

# 4. Making Predictions
y_pred = log_reg.predict(X_test) # Making predictions on the test data

# 5. Evaluating Model Accuracy
accuracy = accuracy_score(y_test, y_pred) # Comparing the predicted labels to the actual test labels
print(f"Logistic Regression model accuracy: {accuracy}")

# Make predictions on new sample data (out-of-sample data)
new_data = [[5.0, 3.6, 1.3, 0.25], [6.5, 3.0, 5.2, 2.0]] # Example new data
predictions = log_reg.predict(new_data)
print(f"Predictions for new data: {iris.target_names[predictions]}")


Logistic Regression model accuracy: 0.9666666666666667
Predictions for new data: ['setosa' 'virginica']


In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

# 1. Prepare Data (example)
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 5, 4, 5])

# 2. Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Instantiate Model
model = LinearRegression()

# 4. Train Model
model.fit(X_train, y_train)

# 5. Make Predictions
predictions = model.predict(X_test)
print(predictions)

# 6. Evaluate Model
mse = mean_squared_error(y_test, predictions)
print(f"Mean Squared Error: {mse}")

[3.14285714]
Mean Squared Error: 0.7346938775510206


In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target variable (species of iris flower)

    # Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier(random_state=42)

    # Train the model
model.fit(X_train, y_train)
print(X_test)
y_pred = model.predict(X_test)
print(y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [6.9 3.1 5.1 2.3]
 [6.2 2.2 4.5 1.5]
 [5.8 2.7 3.9 1.2]
 [6.5 3.2 5.1 2. ]
 [4.8 3.  1.4 0.1]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.8 1.5 0.3]
 [6.3 3.3 4.7 1.6]
 [6.5 3.  5.8 2.2]
 [5.6 2.5 3.9 1.1]
 [5.7 2.8 4.5 1.3]
 [6.4 2.8 5.6 2.2]
 [4.7 3.2 1.6 0.2]
 [6.1 3.  4.9 1.8]
 [5.  3.4 1.6 0.4]
 [6.4 2.8 5.6 2.1]
 [7.9 3.8 6.4 2. ]
 [6.7 3.  5.2 2.3]
 [6.7 2.5 5.8 1.8]
 [6.8 3.2 5.9 2.3]
 [4.8 3.  1.4 0.3]
 [4.8 3.1 1.6 0.2]]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Model Accuracy: 1.00


In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

# Sample data
X = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
y = np.array([2, 4, 5, 4, 6, 7, 8, 9, 10, 11])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.4432966706302026
